### ISSUE TITLE
Timeplan for migration

### ISSUE THREAD

**Issue by eriksven** [eclipse-kuksa/kuksa-databroker#1]
Hello, 
is there a time plan for migrating the code of the Eclipse Kuksa.val Databroker to this repository? 

I am asking because I am wondering which repository to reference when writing future documentation etc.

**Comment by erikbosch** [comment]
@eriksven - @argerus intends to start with it now

**Comment by erikbosch** [comment]
See #2

**Comment by erikbosch** [comment]
Migration finished
